<a href="https://colab.research.google.com/github/Mahiman001/Deep-Learning/blob/main/dl_withpytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [3]:
# CREATING TENSOR

In [4]:
#SCALAR
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# gettiing a tensor backa as a python list

scalar.item()

7

In [7]:
## vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
##MATRIX
matrix =torch.tensor([[7,7],
 [9,10]])
matrix
matrix.ndim

2

In [14]:
tensor = torch.tensor([[[1,2,3],
                      [2,3,4],
                      [5,6,7]]])
tensor

tensor([[[1, 2, 3],
         [2, 3, 4],
         [5, 6, 7]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

here it shows ([1,3,3]),what it means it that there a 1 3x3 tensor


In [17]:
tensor[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]])

In [25]:
## random tensors
random_tensor =torch.rand(3,4)
random_tensor

tensor([[0.7425, 0.1106, 0.9491, 0.5887],
        [0.1899, 0.1005, 0.3525, 0.8520],
        [0.8114, 0.7801, 0.4737, 0.5851]])

In [24]:
random_tensor.ndim

3

In [27]:
## create a random
## tensor with similar shape to an image
random_image_size_tensor =torch.rand(size=(224,224,3))
## HEIGHT, WIDTH, COLOUR CHANNEL
random_image_size_tensor.ndim

3

In [29]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [32]:
## create a tensor of zeros and ones
zeros = torch.zeros(size =(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
zeros.dtype

torch.float32

In [36]:
## torch.range()
x =torch.arange(start =1, end= 12,step =2)
x

tensor([ 1,  3,  5,  7,  9, 11])

In [38]:
###  CREATING TENSOR LIKE method
ssix_zeros =torch.zeros_like(input =x)
ssix_zeros

tensor([0, 0, 0, 0, 0, 0])

In [39]:
    # Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))